import 'css/Global.scss';
import 'css/Variables.css';

import LayoutProvider from 'context/LayoutContext';
import { navigation } from 'data/navigation';
import Navigation from 'layout/Navigation';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pl">
      <LayoutProvider>
      <body className={inter.className}>
        <Navigation
          brand={navigation.brand}
          menu={navigation.menu}
        />
        {children}
      </body>
      </LayoutProvider>
    </html>
  )
}
