export default function Navigation(){
    return(
        <>
            <nav
                style={{
                    backgroundColor:"hsla(0,100%,0%,.8)",
                    color:"#fff",
                    position:"fixed",
                    top:"0",
                    left:"0",
                    width:"100%",
                    height:"9rem",
                    zIndex:999
                }}
            >
                radweb
            </nav>
        </>
    )
}