import 'css/Global.scss';
import LayoutProvider from 'context/LayoutContext';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { navigation } from 'data/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LayoutProvider
        menu={{
          big:navigation.menu.big
        }}
      >
      <body className={inter.className}>
        {children}
      </body>
      </LayoutProvider>
    </html>
  )
}
