import Navigation from "navigation/Navigation";
import StyledComponentsRegistry from "functions/StyledComponentsRegistery";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<html lang="en">
				<StyledComponentsRegistry>
					<body>
						<Navigation />
						{children}
					</body>
				</StyledComponentsRegistry>
			</html>
		</>
	);
}
