import 'css/Global.scss';
import LayoutProvider from 'context/LayoutContext';
import type { Metadata } from 'next';
import { navigation } from 'data/navigation';
import Navigation from 'layout/Navigation';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LayoutProvider
      >
      <body >
        <Navigation 
                brand={navigation.brand}
                menu={{
                    big:navigation.menu.big,
                    small:navigation.menu.small.items
                }} 
                socials={navigation.socials}
                settings={{
                    menuButton:navigation.settings.menuButton
                }}
            />
        {children}
      </body>
      </LayoutProvider>
    </html>
  )
}
