import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "css/Global.scss";
import Navigation from "layout/Navigation";
import MenuProvider from "context/MenuContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "RadWEB",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<MenuProvider>
			<html lang="pl">
				<body className={inter.className}>
					<Navigation />
					{children}
				</body>
			</html>
		</MenuProvider>
	);
}
