import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'css/Global.scss';
import Menu from 'l_navigation/Menu';
import { menu } from 'data/menu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'RadWEB',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pl">
			<Menu menu={menu} />
			<body className={inter.className}>{children}</body>
		</html>
	);
}
