"use client";
import "@default/styles/Global.scss";
import ParticlesWrapper from "@default/components/Utils/Wrappers/ParticlesWrapper";
import MenuProvider from "@default/context/MenuContext";
import Navigation from "@default/components/Layout/Navigation/Navigation";
import content from "@default/content/pl/pages/common.json";
import Footer from "@default/components/Layout/Footer/Footer";
import Newsletter from "@default/components/Layout/Newsletter/Newsletter";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pl">
			<body>
				<ParticlesWrapper />
				<MenuProvider>
					<Navigation
						brand={{
							label: "RadWEB",
							uri: "/",
						}}
						menu={content.navigation}
					/>
					{children}
					<Newsletter />
					<Footer />
				</MenuProvider>
			</body>
		</html>
	);
}
