import Blog from "@default/components/Pages/HomePage/Blog/Blog";
import Hero from "@default/components/Pages/HomePage/Hero/Hero";
import Projects from "@default/components/Pages/HomePage/Projects/Projects";
import Services from "@default/components/Pages/HomePage/Services/Services";
import Statistics from "@default/components/Pages/HomePage/Statistics/Statistics";
import Team from "@default/components/Pages/HomePage/Team/Team";

export const metadata = {
	title: "RadWEB",
	description: "Generated by create next app",
};

export default function Page() {
	return (
		<>
			<Hero
				buttons={[
					{
						label: "blog",
						uri: "#",
					},
					{
						label: "kontakt",
						uri: "#",
					},
				]}
				image={{
					alt: "",
					src: "",
					title: "",
				}}
				slogan="Podbij z nami internet"
				title="RadWEB"
			/>
			<Services />
			<Statistics
				cards={[
					{
						label: "Lat doświadczenia",
						unit: "",
						value: new Date().getFullYear() - 2016,
					},
					{
						label: "Zadowolonych klientów",
						unit: "",
						value: 19,
					},
					{
						label: "Zrealizowane projekty",
						unit: "",
						value: 32,
					},
				]}
			/>
			<Blog />
			<Projects />
			<Team />
		</>
	);
}
