import Navigation from "@layout/Navigation";
import "@css/Global.scss";
import { Inter } from "next/font/google";
import logo from "@assets/logo.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navigation
					brand={{
						image: {
							altText: "RadWEB - Programowanie i SEO | Podbij internet",
							sourceUrl: logo,
							title: "RadWEB - Programowanie i SEO | Podbij internet",
						},
						uri: "/",
					}}
				/>
				{children}
			</body>
		</html>
	);
}
