import Wrapper from "@default/components/Pages/BlogPage/Wrapper/Wrapper";
import Search from "@default/components/Utils/Forms/Search/Search";

export const metadata = {
	title: "RadWEB - Blog - Article",
	description: "Generated by create next app",
};

export default function BlogPage() {
	return (
		<div
			className="hero"
			style={{
				margin: "20rem 0",
			}}
		>
			<Wrapper
				articles={[
					{
						author: {
							fullname: "Radosław Adamczyk",
							image: {
								alt: "",
								src: "https://images.unsplash.com/photo-1580518324671-c2f0833a3af3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
								title: "",
							},
							uri: "/blog",
						},
						category: {
							label: "programowanie",
							uri: "/blog",
						},
						excerpt: `Ipsa qui sapiente est enim nesciunt voluptatem. Laudantium illo aut architecto ipsum laudantium aliquid reprehenderit. Eveniet voluptatem harum accusantium voluptatem sit. Placeat ut est neque voluptatem praesentium ex quae perspiciatis. Odit natus delectus et animi mollitia inventore facilis cum. Quia eum eos odio sint odit adipisci omnis sit.`,
						image: {
							alt: "",
							src: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
							title: "",
						},
						release:
							"Fri Mar 29 2024 21:35:08 GMT+0100 (Central European Standard Time)",
						title: "Jak nauczyć się Reacta - dokumentacje React",
						uri: "/blog",
					},
					{
						author: {
							fullname: "Radosław Adamczyk",
							image: {
								alt: "",
								src: "https://images.unsplash.com/photo-1580518324671-c2f0833a3af3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
								title: "",
							},
							uri: "/blog",
						},
						category: {
							label: "programowanie",
							uri: "/blog",
						},
						excerpt: `Ipsa qui sapiente est enim nesciunt voluptatem. Laudantium illo aut architecto ipsum laudantium aliquid reprehenderit. Eveniet voluptatem harum accusantium voluptatem sit. Placeat ut est neque voluptatem praesentium ex quae perspiciatis. Odit natus delectus et animi mollitia inventore facilis cum. Quia eum eos odio sint odit adipisci omnis sit.`,
						image: {
							alt: "",
							src: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
							title: "",
						},
						release:
							"Fri Mar 29 2024 21:35:08 GMT+0100 (Central European Standard Time)",
						title: "Różnice między tagami HTML a atrybutami i jak ich używać",
						uri: "/blog",
					},
					{
						author: {
							fullname: "Radosław Adamczyk",
							image: {
								alt: "",
								src: "https://images.unsplash.com/photo-1580518324671-c2f0833a3af3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
								title: "",
							},
							uri: "/blog",
						},
						category: {
							label: "programowanie",
							uri: "/blog",
						},
						excerpt: `Ipsa qui sapiente est enim nesciunt voluptatem. Laudantium illo aut architecto ipsum laudantium aliquid reprehenderit. Eveniet voluptatem harum accusantium voluptatem sit. Placeat ut est neque voluptatem praesentium ex quae perspiciatis. Odit natus delectus et animi mollitia inventore facilis cum. Quia eum eos odio sint odit adipisci omnis sit.`,
						image: {
							alt: "",
							src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80",
							title: "",
						},
						release:
							"Fri Mar 29 2024 21:35:08 GMT+0100 (Central European Standard Time)",
						title:
							"Dlaczego dostępność stron internetowych jest ważna dla SEO?",
						uri: "/blog",
					},
					{
						author: {
							fullname: "Radosław Adamczyk",
							image: {
								alt: "",
								src: "https://images.unsplash.com/photo-1580518324671-c2f0833a3af3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
								title: "",
							},
							uri: "/blog",
						},
						category: {
							label: "programowanie",
							uri: "/blog",
						},
						excerpt: `Ipsa qui sapiente est enim nesciunt voluptatem. Laudantium illo aut architecto ipsum laudantium aliquid reprehenderit. Eveniet voluptatem harum accusantium voluptatem sit. Placeat ut est neque voluptatem praesentium ex quae perspiciatis. Odit natus delectus et animi mollitia inventore facilis cum. Quia eum eos odio sint odit adipisci omnis sit.`,
						image: {
							alt: "",
							src: "https://images.unsplash.com/photo-1519241047957-be31d7379a5d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
							title: "",
						},
						release:
							"Fri Mar 29 2024 21:35:08 GMT+0100 (Central European Standard Time)",
						title: "Jak zwiększyć widoczność swojego biznesu z lokalnym SEO?",
						uri: "/blog",
					},
					{
						author: {
							fullname: "Radosław Adamczyk",
							image: {
								alt: "",
								src: "https://images.unsplash.com/photo-1580518324671-c2f0833a3af3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
								title: "",
							},
							uri: "/blog",
						},
						category: {
							label: "programowanie",
							uri: "/blog",
						},
						excerpt: `Ipsa qui sapiente est enim nesciunt voluptatem. Laudantium illo aut architecto ipsum laudantium aliquid reprehenderit. Eveniet voluptatem harum accusantium voluptatem sit. Placeat ut est neque voluptatem praesentium ex quae perspiciatis. Odit natus delectus et animi mollitia inventore facilis cum. Quia eum eos odio sint odit adipisci omnis sit.`,
						image: {
							alt: "",
							src: "https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
							title: "",
						},
						release:
							"Fri Mar 29 2024 21:35:08 GMT+0100 (Central European Standard Time)",
						title:
							"Robots.txt — Jak przejąć kontrolę nad robotami wyszukiwarek?",
						uri: "/blog",
					},
				]}
			>
				<Search />
			</Wrapper>
		</div>
	);
}
