import MobileNavigation from 'layout/MobileNavigation';
import 'css/Global.scss';
import { Inter } from 'next/font/google';
import { mobileNavigation } from 'data/mobileNavigation';
import Navigation from 'layout/Navigation';
import { menu } from 'data/menu';

const inter = Inter({ subsets: ['latin'] });
export const metadata = {
	title: 'RadWEB',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<Navigation
					brand={{
						label: 'Rad<br/>WEB',
						uri: '#',
					}}
					menu={{
						menu: menu,
					}}
				/>
				{children}
				<MobileNavigation menu={mobileNavigation} />
			</body>
		</html>
	);
}
